# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Clement Demonchy
title: Data Emngineer
website: https://knil-sama.github.io/cdemonchy/

# Social links
twitter_username: knil_sama
github_username:  knil-sama
instagram_username: knilsama
linkedin_username: clement-demonchy-55327778

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
Data engineer @Jobteaser, python enthusiast and cat lover
  I am most skilled in: <mark>AWS</mark>, <mark>Python</mark>, <mark>PostgreSQL</mark> and <mark>Kubernetes</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Article Section
# article_title: Article

# Presentation Section
# presentation_title: Presentation

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Triathlon
   - Cooking
   - Gaming
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
