# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Clement Demonchy
title: Data Engineer

# Social links
twitter_username: knil_sama
github_username:  knil-sama
instagram_username: knilsama
linkedin_username: clement-demonchy-55327778

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Data engineer at Jobteaser, python enthusiast and cat lover  
  I am most skilled in: <mark>AWS</mark>, <mark>Python</mark>, <mark>PostgreSQL</mark> and <mark>Kubernetes</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

more_content: | # this will include new lines to allow paragraphs
  Articles  
  - [Autoscaling in DynamoDB using boto3](https://medium.com/@cols.knil/autoscaling-in-dynamodb-with-boto3-bf5bbeb99b10)
  - [Python Packaging : How we manage it at JobTeaser](https://medium.com/jobteaser-dev-team/python-packaging-how-do-we-manage-it-at-jobteaser-2bc8d1e9d206i)
  - [Kubernetes Cronjob 101 part 1](https://medium.com/jobteaser-dev-team/kubernetes-cronjob-101-56f0a8ea7ca2)
  - [Kubernetes Cronjob 101 part 2](https://medium.com/@cols.knil/cronjob-101-part-2-78503d3967b3)

  Presentation  
  - [From Mysql to PostgreSQL using Debezium](https://www.slideshare.net/ClementDemonchy/from-my-sql-to-postgresql-using-kafkadebezium)
  - [Kafka 101](https://www.slideshare.net/ClementDemonchy/kafka-101)
      
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Triathlon
   - Cooking
   - Gaming
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
