name: Build Jekyll site
on:
  push:
#    branches: ["main"]
env:
  AWS_REGION: us-east-1
  CLOUD_FRONT_DISTRIBUTION_ID: EQ9X221SJSDOP
  S3_BUCKET: aws-website-demonchy-5v3aj
  AWS_ACCOUNT_ID: 650593633156
  ROLE_UPDATE_WEBSITE: cdemonchy-website-update
# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/resume/Gemfile
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.153.0
      with:
        ruby-version: "3.0" # Not needed with a .ruby-version file
        bundler-cache: true
    - name: "Build Site"
      run: |
        cd resume
        bundle exec jekyll build
      env:
        JEKYLL_ENV: production
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4.0.0
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.ROLE_UPDATE_WEBSITE }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}
    - name: "Deploy to AWS S3"
      run: aws s3 sync ./resume/_site/ s3://${{ env.S3_BUCKET }} --delete --cache-control max-age=604800
    - name: "Create AWS Cloudfront Invalidation"
      run: aws cloudfront create-invalidation --distribution-id ${{ env.CLOUD_FRONT_DISTRIBUTION_ID }} --paths "/*"

