name: Build docusaurus blog
on:
  push:
#    branches: ["main"]
env:
  AWS_REGION: us-east-1
  CLOUD_FRONT_DISTRIBUTION_ID: EQ9X221SJSDOP
  S3_BUCKET: aws-website-demonchy-5v3aj
  AWS_ACCOUNT_ID: 650593633156
  ROLE_UPDATE_WEBSITE: cdemonchy-website-update
# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # 👇 Build steps
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: 18.x
        cache-dependency-path: 'blog/website/package-lock.json'
    - name: Install dependencies
      run: |
        cd blog/website
        npm install --frozen-lockfile --non-interactive
    - name: Build
      run: |
        cd blog/website
        npm build
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4.0.0
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.ROLE_UPDATE_WEBSITE }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}
    - name: "Deploy to AWS S3"
      run: |
        rm .blog/website/blog/website/build/cdw/index.html # need to remove this root index to avoid conflict with resume
        aws s3 sync ./blog/website/build/cdw s3://${{ env.S3_BUCKET }} --delete --cache-control max-age=604800
    - name: "Create AWS Cloudfront Invalidation"
      run: aws cloudfront create-invalidation --distribution-id ${{ env.CLOUD_FRONT_DISTRIBUTION_ID }} --paths "/*"

